# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'activerecord-import'
gem 'autoprefixer-rails'
gem 'autosize-rails'
gem 'aws-sdk', '~> 2.1'
gem 'axios_rails'
gem 'binding_of_caller'
gem 'bootstrap', '~> 4.3.1'
gem 'bootstrap-datepicker-rails'
gem 'browserify-rails'
gem 'carrierwave'
gem 'chatwork'
gem 'composite_primary_keys'
gem 'config'
gem 'devise'
gem 'devise-i18n'
gem 'dotenv-rails'
gem 'es6-promise-rails'
gem 'faraday'
gem 'fog-aws'
gem 'font-awesome-rails'
gem 'gon'
gem 'google-api-client'
gem 'grape'
gem 'gretel'
gem 'hiredis'
gem 'holiday_jp'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'kaminari', '~> 0.17.0'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem 'meta-tags'
gem 'mini_racer'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'net-scp'
gem 'net-ssh'
gem 'octokit'
gem 'omniauth-google-oauth2'
gem 'paper_trail'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.1'
gem 'rails-i18n'
gem 'ransack'
gem 'rb-readline'
gem 'redis', '~> 4.0.1'
gem 'roboto'
gem 'rubocop-performance'
gem 'sass-rails', '~> 5.0'
gem 'seed-fu'
gem 'sendgrid-ruby'
gem 'serviceworker-rails'
gem 'simple_form'
gem 'sitemap_generator'
gem 'slim-rails'
gem 'twitter'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'uglifier', '>= 1.3.0'
gem 'vuejs-rails'
gem 'whenever', require: false
gem 'zeroclipboard-rails'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'rubocop-rspec'
  gem 'simplecov'
  gem 'test-prof'
  gem 'yard'
end

group :development do
  gem 'activerecord-commentator'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'bullet'
  gem 'database_cleaner'
  gem 'database_rewinder'
  gem 'guard-rspec'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'tapp'
  gem 'web-console', '>= 3.3.0'
end
