# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '7.0.3'

gem 'activerecord-import'
gem 'autoprefixer-rails'
gem 'autosize-rails'
gem 'aws-sdk'
gem 'axios_rails'
gem 'binding_of_caller'
gem 'bootstrap'
gem 'bootstrap-datepicker-rails'
gem 'browserify-rails'
gem 'carrierwave'
gem 'chatwork'
gem 'composite_primary_keys'
gem 'config'
gem 'devise'
gem 'devise-i18n'
gem 'dotenv-rails'
gem 'es6-promise-rails'
gem 'faraday'
gem 'fog-aws'
gem 'font-awesome-rails'
gem 'gon'
gem 'google-api-client'
gem 'grape'
gem 'gretel'
gem 'holiday_jp'
gem 'jquery-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'meta-tags'
gem 'mini_racer'
gem 'mysql2'
gem 'net-scp'
gem 'net-ssh'
gem 'octokit'
gem 'omniauth-google-oauth2'
gem 'paper_trail'
gem 'puma'
gem 'rails-i18n'
gem 'ransack'
gem 'rb-readline'
gem 'redis'
gem 'roboto'
gem 'rubocop-performance'
gem 'sass-rails'
gem 'seed-fu'
gem 'sendgrid-ruby'
gem 'serviceworker-rails'
gem 'simple_form'
gem 'sitemap_generator'
gem 'slim-rails'
gem 'twitter'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'uglifier'
gem 'vuejs-rails'
gem 'whenever', require: false
gem 'zeroclipboard-rails'
gem 'lazyload-rails'
gem 'rack-user_agent'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'rubocop-rspec'
  gem 'simplecov'
  gem 'codecov', :require => false, :group => :test
  gem 'test-prof'
  gem 'yard'
end

group :development do
  gem 'activerecord-commentator'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'bullet'
  gem 'database_cleaner'
  gem 'database_rewinder'
  gem 'guard-rspec'
  gem 'listen'
  gem 'tapp'
  gem 'web-console'
  gem "letter_opener"
  gem 'letter_opener_web'
end
